services:
  backend:
    depends_on:
      - db
    env_file:
      - .env
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "pip install --no-cache-dir -r backend/requirements.txt && python -m backend.main"
    ports:
      - "5000:5000"

  frontend:
    depends_on:
      - backend
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "pip install --no-cache-dir streamlit requests && streamlit run frontend/app.py --server.address=0.0.0.0 --server.port=8501"
    environment:
      - API_BASE=http://backend:5000
    ports:
      - "8501:8501"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

